url: https://github.com/sowomo123/sonamwangmo.github.io

github:
 username: sowomo123

facebook:
 username: sonam Wangmo

social:
 name: Sonam Wangmo
 email: 02240363.cst@rub.edu.bt

 links:
 - https://www.facebook.com/share/1AmYwc9dT8/
 - https://github.com/sowomo123

 